channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.3.1
- pip:
  - mlflow==2.17.1
  - cloudpickle==3.1.0
  - numpy==2.1.2
  - pandas==2.2.3
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
